#!/usr/bin/env bash
set -ex

# Assets
npm install
npm run prod

# Jekyll
bundle exec jekyll doctor
bundle exec jekyll build

# Check HTML
bundle exec htmlproofer ./dist \
  --check-html \
  --http-status-ignore 301,302 \
  --url-ignore "/mlo.io/" \
  --assume-extension
